config/routes.rb
Myfamilysinfo::Application.routes.draw do

  root :to => "home#index"
 devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}


  get ':users/:id/', :to => "user#show"

  #resources :users, :path => "user"
  resource :user, { controller: :users, only: :show } do
    resources :kids, only: [:new, :create] do
      resources :reminders, only: [:new, :create] do
      end
    end
  end
  resources :kids, only: [:destroy]
  resources :reminders, only: [:destroy, :update]
end

app/models/kid.rb
class Kid < ActiveRecord::Base
  has_many :relationships
  has_many :users, through: :relationships
  has_many :reminders
  accepts_nested_attributes_for :relationships
end

app/models/record.rb
class Record < ActiveRecord::Base
  belongs_to :kid
  has_many :users, through: :kids
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :user
  belongs_to :kid

  scope :father, -> { where(role: 'Father')}
  scope :mother, -> { where(role: 'Mother')}

  def self.sort_by_role
    self.map do |relationship|
      role = relationship.role
      self.select { |r| r.role == role }
    end
  end

end

app/models/reminder.rb
class Reminder < ActiveRecord::Base
  belongs_to :kid
  has_many :users, through: :kids
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable

  # validates_presence_of :username
  # validates_uniqueness_of :username

  has_many :relationships
  has_many :kids, through: :relationships
  has_many :reminders, through: :kids

  def self.sort_by_role(user)
    roles = user.relationships.map { |relationship| relationship.role }
    roles.uniq do |role|
      user.relationships.select { |r| r.role == role }
    end
  end


  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.nickname
      user.email = "#{user.name}-CHANGEME@twitter.example.com"
    end
  end

  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"], without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  def email_required?
    super && provider.blank?
  end

  def password_required?
    super && provider.blank?
  end

  def update_with_password(params, *options)
    if encrypted_password.blank?
      update_attributes(params, *options)
    else
      super
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception
  def after_sign_in_path_for(resource)
    user_path
  end

  # private
  # def current_user
  #   @current_user ||= User.find(session[:user_id]) if session[:user_id]
  # end
  # helper_method :current_user
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/kids_controller.rb
class KidsController < ApplicationController
  before_filter :authenticate_user!

  def new
    @user = current_user
    @kid = Kid.new
    @kid.relationships.build
  end

  def create
     new_params = kid_params.merge("relationships_attributes" => { "0" => {"user_id" => current_user.id}})
     nested_params = kid_params.deep_merge(new_params)
     @kid = Kid.create(nested_params)
     # authorize @kid
     redirect_to user_path, notice: "#{@kid.name} was added your account"
  end

  def destroy
    @kid = Kid.find(params[:id])
    @kid.destroy
    redirect_to user_path, notice: "#{@kid.name} was removed from your account"
  end


  private
    def kid_params
      params.require(:kid).permit(:name, :user_id, relationships_attributes: [:role, :user_id])
    end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def all
    user = User.from_omniauth(request.env["omniauth.auth"])
    if user.persisted?
      flash.notice = "#{user.name}, you are signed in!"
      sign_in_and_redirect user, notice: "#{user.name}, you are signed in!"
    else
      session["devise.user_attributes"] = user.attributes
      redirect_to new_user_registration_url
    end
  end
  alias_method :twitter, :all
  alias_method :facebook, :all
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_filter :update_sanitized_params, if: :devise_controller?

  def update_sanitized_params
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:email, :password, :password_confirmation)}
    devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:email, :password, :password_confirmation, :current_password)}
  end

end

app/controllers/reminders_controller.rb
class RemindersController < ApplicationController
  before_filter :authenticate_user!

  def new
    @kid = Kid.find(params[:kid_id])
    @reminder = @kid.reminders.build
  end

  def create
    @kid = Kid.find(params[:kid_id])
    @reminder = @kid.reminders.create(reminder_params)
    if @reminder.save
      redirect_to user_path, notice: "#{@reminder.name} added for #{@kid.name}!"
    else
      render :new
    end
  end

  def update
    @reminder = Reminder.find(params[:id])
    @reminder.touch
    redirect_to user_path, notice: "#{@reminder.name} reminder was updated!"
  end

  def destroy
    @reminder = Reminder.find(params[:id])
    @reminder.destroy
    redirect_to user_path, notice: "#{@reminder.name} reminder was deleted!"
  end

  private
    def reminder_params
      params.require(:reminder).permit(:name, :kid_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def show
    @user = !params[:id].nil? ? User.find(params[:id]) : current_user

    #authorize @user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kid_helper.rb
module KidHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/reminders_helper.rb
module RemindersHelper
end

app/views/home/index.html.erb
      <div class="row">
        <div class="large-12 columns">
          <div class="row">
            <!-- Shows -->
            <div class="large-8 small-6 columns">
<dl class="tabs vertical" data-tab style="width: 30%">
  <dd><a href="#">Kids</a></dd>
  <dd class="active"><a href="#kid1">Mikey</a></dd>
  <dd><a href="#kid2">Susy</a></dd>
  <dd><a href="#kid3">Jodey</a></dd>
  <dd><a href="#kid4">Brandon</a></dd>
</dl>
<div class="tabs-content vertical panel text-center" align="left" style="float: right; width: 70%">
  <div class="content active " id="kid1">
                <h5><a href="#">Use our App!</a></h5>
                <h6 class="subheader">
                  First click add a kid, then click add a reminder, then you are rockin!
                </h6>
                <h6><a href="#">Sign Up Now! </a></h6>
  </div>
  <div class="content" id="kid2">
    <h5><a href="#">Use our App!</a></h5>
                <h6 class="subheader">
                  First click add a kid, then click add a reminder, then you are rockin!
                </h6>
                <h6><a href="#">Sign Up Now! </a></h6>
  </div>
  <div class="content" id="kid3">
                <h5><a href="#">Use our App!</a></h5>
                <h6 class="subheader">
                  First click add a kid, then click add a reminder, then you are rockin!
                </h6>
                <h6><a href="#">Sign Up Now! </a></h6>
  </div>
  <div class="content" id="kid4">
                <h5><a href="#">Use our App!</a></h5>
                <h6 class="subheader">
                  First click add a kid, then click add a reminder, then you are rockin!
                </h6>
                <h6><a href="#">Sign Up Now! </a></h6>
  </div>
</div>
</div>
            <div class="large-4 small-12 columns">


              <div class="text-center panel hide-for-small">
                <%= link_to '#', class: "custom-success" do  %>
                  Add a kid: <i class="fi-torsos-all"></i>
                  <% end %>
              </div>



            </div>
    </div>
    </div>

  </div>

app/views/kids/create.html.erb
<h1>Kid#create</h1>
<p>Find me in app/views/kid/create.html.erb</p>

app/views/kids/new.html.erb
  <div class="row">

    <!-- Contact Details -->
    <div class="large-9 panel columns">

      <h3>Add a Kid!</h3>
      <p>Simply put your kids name in the field below, hit add and you are golden!</em></p>
        <a>

                 <h1>Kiddo</h1>
          <%= form_for [:user, @kid] do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name %>
        <button class="radius button" type="submit">Add</button>
             <% end %>
             </div>
             </div>

app/views/kids/new.js.erb
$("#new_grouping").html("<%= escape_javascript(...) %>">
<h1>Add Kid</h1>


<%= form_for [:user, @kid] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.fields_for :relationships do |r| %>
    <%= r.select :role, options_for_select(["Mother","Father"]) %>
    <%# r.input :user, as: :hidden, input_html: { value: current_user } %>
  <% end %>

  <%= f.submit %>
<% end %>

app/views/layouts/_facebooklikes.html.erb
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=351451988331148";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name == :notice ? "success" : "alert" %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <% if user_signed_in?  %>
      <li class="name"><%= link_to 'Home', user_path %></li>
    <% else %>
      <li class="name"><%= link_to 'Home', root_path %></li>
    <% end %>
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>
  <div class="top-bar-section">
    <ul>
      <%= render 'layouts/navigation_links' %>
    </ul>
   <ul class="right">
    <% if current_user %>
          <li class="divider"></li>
              <li>
                <%= link_to "Signed in as #{current_user.email}", user_path(current_user) %>
                <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
              </li>
    <% end %>
  </ul>
    </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>

<% else %>
  <li><%= link_to "Sign in with Twitter", user_omniauth_authorize_path(:twitter) %></li>
  <li><%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %></li>
  <li><%= link_to 'Login', new_user_session_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
<% else %>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/_tag.html.erb
<!-- Google Tag Manager -->
<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-MX9DB2"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-MX9DB2');</script>
<!-- End Google Tag Manager -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Myfamilysinfo" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Myfamilysinfo" %>">
    <%= render 'layouts/tag' %>
    <%= stylesheet_link_tag "application", media: "all" %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>

  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
       <%= render 'layouts/messages' %>
       <%= render 'layouts/facebooklikes' %>
       <%= yield %>
      <footer class="row">
        <div class="large-12 columns">
            <div class="row">

              <div class="large-6 columns">
                  <div class="fb-like" data-href="https://www.facebook.com/myfamilysinfo" data-layout="standard" data-action="like" data-show-faces="true" data-share="true"></div>
                  <p>&copy; Copyright no one at all. Go to town.</p>
              </div>

              </div>

            </div>
        </div>
      </footer>

    <!-- End Footer -->

    </div>
  </div>

  </body>
</html>

app/views/reminders/new.html.erb
  <div class="row">

    <!-- Contact Details -->
    <div class="large-9 panel columns">

      <h3>Add a Reminder!</h3>
      <p>Put in anything you like! </em></p>
        <a>

        <h2>Reminder For <%= @kid.name %></h2>
        <%= simple_form_for [:user, @kid, @reminder] do |f| %>
        <%= f.input :name, label: 'What are you going to give me?' %>
        <button class="radius button" type="submit">Add</button>
             <% end %>
     </div>
     </div>

app/views/users/index.html.erb
<h3>Users</h3>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.email, user %> signed up <%= user.created_at.to_date %>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<% user_kids = @user.kids.includes(:reminders) %>
      <div class="row">
        <div class="large-12 columns">
          <div class="row">
            <!-- Shows -->
            <div class="large-8 small-6 columns">


<dl class="tabs vertical" data-tab style="width: 30%">
  
  <dd>
    <%= link_to 'Kids', "#"  %>
  </dd>
  <% user_kids.each_with_index do |kid, i| %>
    <% if i == 0 %>
      <dd class="active"><%= link_to kid.name.titleize, "#kid-#{i+1}" %></dd>
    <% else %>
      <dd><%= link_to kid.name.titleize, "#kid-#{i+1}" %></dd>
    <% end %>
  <% end %>
</dl>




            <!-- Image -->

            <div class="tabs-content panel" align="left" style="float: right; width: 70%">
  <% user_kids.each_with_index do |kid, i| %>
    <% if i == 0 %>
      <div class="content active" id="kid<%= "-#{i+1}" %>">
    <% else %>
      <div class="content" id="kid<%= "-#{i+1}" %>">
    <% end %>
              <ul class="button-group radius">
                <li>
                  <span data-tooltip class="has-tip" title="<%= "Click here to add a reminder for #{kid.name}"  %>">
                    <%= link_to((new_user_kid_reminder_path [kid]), class: "button  radius tiny custom-success") do %>
                      <i class="fi-plus"></i>
                    <% end %>
                  </span>
                </li>
                <li>
                  <span data-tooltip class="has-tip" title="<%= "Click here to remove #{kid.name}"  %>">
                    <%= link_to(kid, method: :delete, data: { confirm: "are you sure?"}, class: "button radius tiny custom-alert") do %>
                      <i class="fi-torso"></i>
                    <% end %>
                  </span>
                </li>
                <li class="right">
                <h6>
                  <%= kid.name  %>'s reminders
                </h6>
                </li>
              </ul>
            <% kid.reminders.each do |reminder| %>
              <ul class="button-group radius">
                <li>
                <%= form_for reminder do |f| %>
                  <%= button_tag(type: 'submit', class: "button tiny radius custom-primary") do %>
                    <i class="fi-refresh"></i>
                  <% end %>
                <% end %>
                </li>
                <li >
                <%= link_to reminder, method: :delete, data: { confirm: "Are you sure?"}, class: "button tiny radius custom-alert" do  %>
                  <i class="fi-x"></i>
                <% end %>
                </li>
              <li class="left">
                <h6> &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp ... took <strong><%= reminder.name %></strong> <%= time_ago_in_words(reminder.updated_at) %> ago</h6>
              </li>
              </ul>
              <% end %>
      </div>
    <% end %>
            </div>

            </div>
            <!-- End Image -->


            <!-- Feed -->

            <div class="large-4 small-12 columns">


              <div class="text-center panel hide-for-small">
                <%= link_to new_user_kid_path, class: "custom-success" do  %>
                  Add a kid: <i class="fi-torsos-all"></i>
                  <% end %>
              </div>



            </div>


          </div>
        </div>

      </div>
      </div>